version: '3.2'

services:
  factomd:
    container_name: factomd_container
    image: factominc/factomd:latest
    entrypoint: /go/bin/factomd
    command: '--network=LOCAL --blktime=15'
    restart: unless-stopped
    ports:
      - "8110:8110"
      - "8109:8109"
      - "8108:8108"
      - "8090:8090"
      - "8088:8088"
    volumes:
      - factomd_volume:/root/.factom/

  walletd:
    container_name: walletd_container
    image: factominc/factom-walletd:alpine
    restart: unless-stopped
    ports:
      - "8089:8089"
    volumes:
      - walletd_volume:/root/.factom/
      - ./config/factomd.conf:/root/.factom/m2/factomd.conf:ro
    depends_on:
      - factomd

  pegnet:
    container_name: pegnet_container
    build: .
    ports:
      - "8080:8080"
      - "8099:8099"
    volumes:
      - .:/go/src/github.com/pegnet/pegnet
      - ./lxrhash:/root/.lxrhash
      - ./config/pegnetconfig.ini:/root/.pegnet/defaultconfig.ini:ro

volumes:
  factomd_volume:
  walletd_volume: