version: '3.2'

services:
  walletd:
    container_name: walletd_container
    image: factominc/factom-walletd:alpine
    restart: unless-stopped
    ports:
      - "8089:8089"
    volumes:
      - walletd_volume:/root/.factom/
      - ./config/factomd.conf:/root/.factom/m2/factomd.conf:ro

volumes:
  walletd_volume: