// Code generated by protoc-gen-go. DO NOT EDIT.
// source: opr.proto

package oprencoding

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProtoOPR struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Height               int32    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Winners              []string `protobuf:"bytes,4,rep,name=winners,proto3" json:"winners,omitempty"`
	Assets               *Assets  `protobuf:"bytes,5,opt,name=assets,proto3" json:"assets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoOPR) Reset()         { *m = ProtoOPR{} }
func (m *ProtoOPR) String() string { return proto.CompactTextString(m) }
func (*ProtoOPR) ProtoMessage()    {}
func (*ProtoOPR) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c939583bc8284b5, []int{0}
}

func (m *ProtoOPR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoOPR.Unmarshal(m, b)
}
func (m *ProtoOPR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoOPR.Marshal(b, m, deterministic)
}
func (m *ProtoOPR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoOPR.Merge(m, src)
}
func (m *ProtoOPR) XXX_Size() int {
	return xxx_messageInfo_ProtoOPR.Size(m)
}
func (m *ProtoOPR) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoOPR.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoOPR proto.InternalMessageInfo

func (m *ProtoOPR) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ProtoOPR) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProtoOPR) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ProtoOPR) GetWinners() []string {
	if m != nil {
		return m.Winners
	}
	return nil
}

func (m *ProtoOPR) GetAssets() *Assets {
	if m != nil {
		return m.Assets
	}
	return nil
}

type Assets struct {
	PEG                  uint64   `protobuf:"varint,5,opt,name=PEG,proto3" json:"PEG,omitempty"`
	PUSD                 uint64   `protobuf:"varint,6,opt,name=pUSD,proto3" json:"pUSD,omitempty"`
	PEUR                 uint64   `protobuf:"varint,7,opt,name=pEUR,proto3" json:"pEUR,omitempty"`
	PJPY                 uint64   `protobuf:"varint,8,opt,name=pJPY,proto3" json:"pJPY,omitempty"`
	PGBP                 uint64   `protobuf:"varint,9,opt,name=pGBP,proto3" json:"pGBP,omitempty"`
	PCAD                 uint64   `protobuf:"varint,10,opt,name=pCAD,proto3" json:"pCAD,omitempty"`
	PCHF                 uint64   `protobuf:"varint,11,opt,name=pCHF,proto3" json:"pCHF,omitempty"`
	PINR                 uint64   `protobuf:"varint,12,opt,name=pINR,proto3" json:"pINR,omitempty"`
	PSGD                 uint64   `protobuf:"varint,13,opt,name=pSGD,proto3" json:"pSGD,omitempty"`
	PCNY                 uint64   `protobuf:"varint,14,opt,name=pCNY,proto3" json:"pCNY,omitempty"`
	PHKD                 uint64   `protobuf:"varint,15,opt,name=pHKD,proto3" json:"pHKD,omitempty"`
	PKRW                 uint64   `protobuf:"varint,16,opt,name=pKRW,proto3" json:"pKRW,omitempty"`
	PBRL                 uint64   `protobuf:"varint,17,opt,name=pBRL,proto3" json:"pBRL,omitempty"`
	PPHP                 uint64   `protobuf:"varint,18,opt,name=pPHP,proto3" json:"pPHP,omitempty"`
	PMXN                 uint64   `protobuf:"varint,19,opt,name=pMXN,proto3" json:"pMXN,omitempty"`
	PXAU                 uint64   `protobuf:"varint,20,opt,name=pXAU,proto3" json:"pXAU,omitempty"`
	PXAG                 uint64   `protobuf:"varint,21,opt,name=pXAG,proto3" json:"pXAG,omitempty"`
	PXBT                 uint64   `protobuf:"varint,22,opt,name=pXBT,proto3" json:"pXBT,omitempty"`
	PETH                 uint64   `protobuf:"varint,23,opt,name=pETH,proto3" json:"pETH,omitempty"`
	PLTC                 uint64   `protobuf:"varint,24,opt,name=pLTC,proto3" json:"pLTC,omitempty"`
	PRVN                 uint64   `protobuf:"varint,25,opt,name=pRVN,proto3" json:"pRVN,omitempty"`
	PXBC                 uint64   `protobuf:"varint,26,opt,name=pXBC,proto3" json:"pXBC,omitempty"`
	PFCT                 uint64   `protobuf:"varint,27,opt,name=pFCT,proto3" json:"pFCT,omitempty"`
	PBNB                 uint64   `protobuf:"varint,28,opt,name=pBNB,proto3" json:"pBNB,omitempty"`
	PXLM                 uint64   `protobuf:"varint,29,opt,name=pXLM,proto3" json:"pXLM,omitempty"`
	PADA                 uint64   `protobuf:"varint,30,opt,name=pADA,proto3" json:"pADA,omitempty"`
	PXMR                 uint64   `protobuf:"varint,31,opt,name=pXMR,proto3" json:"pXMR,omitempty"`
	PDASH                uint64   `protobuf:"varint,32,opt,name=pDASH,proto3" json:"pDASH,omitempty"`
	PZEC                 uint64   `protobuf:"varint,33,opt,name=pZEC,proto3" json:"pZEC,omitempty"`
	PDCR                 uint64   `protobuf:"varint,34,opt,name=pDCR,proto3" json:"pDCR,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Assets) Reset()         { *m = Assets{} }
func (m *Assets) String() string { return proto.CompactTextString(m) }
func (*Assets) ProtoMessage()    {}
func (*Assets) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c939583bc8284b5, []int{1}
}

func (m *Assets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Assets.Unmarshal(m, b)
}
func (m *Assets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Assets.Marshal(b, m, deterministic)
}
func (m *Assets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Assets.Merge(m, src)
}
func (m *Assets) XXX_Size() int {
	return xxx_messageInfo_Assets.Size(m)
}
func (m *Assets) XXX_DiscardUnknown() {
	xxx_messageInfo_Assets.DiscardUnknown(m)
}

var xxx_messageInfo_Assets proto.InternalMessageInfo

func (m *Assets) GetPEG() uint64 {
	if m != nil {
		return m.PEG
	}
	return 0
}

func (m *Assets) GetPUSD() uint64 {
	if m != nil {
		return m.PUSD
	}
	return 0
}

func (m *Assets) GetPEUR() uint64 {
	if m != nil {
		return m.PEUR
	}
	return 0
}

func (m *Assets) GetPJPY() uint64 {
	if m != nil {
		return m.PJPY
	}
	return 0
}

func (m *Assets) GetPGBP() uint64 {
	if m != nil {
		return m.PGBP
	}
	return 0
}

func (m *Assets) GetPCAD() uint64 {
	if m != nil {
		return m.PCAD
	}
	return 0
}

func (m *Assets) GetPCHF() uint64 {
	if m != nil {
		return m.PCHF
	}
	return 0
}

func (m *Assets) GetPINR() uint64 {
	if m != nil {
		return m.PINR
	}
	return 0
}

func (m *Assets) GetPSGD() uint64 {
	if m != nil {
		return m.PSGD
	}
	return 0
}

func (m *Assets) GetPCNY() uint64 {
	if m != nil {
		return m.PCNY
	}
	return 0
}

func (m *Assets) GetPHKD() uint64 {
	if m != nil {
		return m.PHKD
	}
	return 0
}

func (m *Assets) GetPKRW() uint64 {
	if m != nil {
		return m.PKRW
	}
	return 0
}

func (m *Assets) GetPBRL() uint64 {
	if m != nil {
		return m.PBRL
	}
	return 0
}

func (m *Assets) GetPPHP() uint64 {
	if m != nil {
		return m.PPHP
	}
	return 0
}

func (m *Assets) GetPMXN() uint64 {
	if m != nil {
		return m.PMXN
	}
	return 0
}

func (m *Assets) GetPXAU() uint64 {
	if m != nil {
		return m.PXAU
	}
	return 0
}

func (m *Assets) GetPXAG() uint64 {
	if m != nil {
		return m.PXAG
	}
	return 0
}

func (m *Assets) GetPXBT() uint64 {
	if m != nil {
		return m.PXBT
	}
	return 0
}

func (m *Assets) GetPETH() uint64 {
	if m != nil {
		return m.PETH
	}
	return 0
}

func (m *Assets) GetPLTC() uint64 {
	if m != nil {
		return m.PLTC
	}
	return 0
}

func (m *Assets) GetPRVN() uint64 {
	if m != nil {
		return m.PRVN
	}
	return 0
}

func (m *Assets) GetPXBC() uint64 {
	if m != nil {
		return m.PXBC
	}
	return 0
}

func (m *Assets) GetPFCT() uint64 {
	if m != nil {
		return m.PFCT
	}
	return 0
}

func (m *Assets) GetPBNB() uint64 {
	if m != nil {
		return m.PBNB
	}
	return 0
}

func (m *Assets) GetPXLM() uint64 {
	if m != nil {
		return m.PXLM
	}
	return 0
}

func (m *Assets) GetPADA() uint64 {
	if m != nil {
		return m.PADA
	}
	return 0
}

func (m *Assets) GetPXMR() uint64 {
	if m != nil {
		return m.PXMR
	}
	return 0
}

func (m *Assets) GetPDASH() uint64 {
	if m != nil {
		return m.PDASH
	}
	return 0
}

func (m *Assets) GetPZEC() uint64 {
	if m != nil {
		return m.PZEC
	}
	return 0
}

func (m *Assets) GetPDCR() uint64 {
	if m != nil {
		return m.PDCR
	}
	return 0
}

func init() {
	proto.RegisterType((*ProtoOPR)(nil), "oprencoding.ProtoOPR")
	proto.RegisterType((*Assets)(nil), "oprencoding.Assets")
}

func init() { proto.RegisterFile("opr.proto", fileDescriptor_9c939583bc8284b5) }

var fileDescriptor_9c939583bc8284b5 = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xd3, 0xdb, 0x6e, 0x9b, 0x4c,
	0x10, 0x07, 0x70, 0xe1, 0x03, 0x89, 0xd7, 0xdf, 0x97, 0xa6, 0x9b, 0x34, 0x9d, 0x9e, 0xa9, 0xaf,
	0x2c, 0x55, 0xf2, 0x45, 0xfb, 0x04, 0xbb, 0x0b, 0x86, 0xc4, 0x40, 0x57, 0x6b, 0x48, 0x70, 0xee,
	0xd2, 0x82, 0x12, 0x6e, 0x0c, 0x02, 0x4b, 0x7d, 0x90, 0xbe, 0x60, 0x1f, 0xa5, 0xf2, 0xec, 0x10,
	0xf5, 0x6e, 0xe7, 0xe7, 0xff, 0xcc, 0xac, 0x57, 0x82, 0xcd, 0x9a, 0xb6, 0x5b, 0xb5, 0x5d, 0x73,
	0x68, 0xf8, 0xbc, 0x69, 0xbb, 0x6a, 0xff, 0xb3, 0x29, 0xeb, 0xfd, 0xe3, 0xe2, 0xb7, 0xc3, 0x4e,
	0xf5, 0x91, 0xbf, 0x6b, 0xc3, 0x81, 0x9d, 0x3c, 0x94, 0x65, 0x57, 0xf5, 0x3d, 0x38, 0x9e, 0xb3,
	0x9c, 0x99, 0xa1, 0xe4, 0x67, 0x6c, 0x54, 0x97, 0x30, 0x42, 0x1c, 0xd5, 0x25, 0xbf, 0x62, 0xee,
	0x53, 0x55, 0x3f, 0x3e, 0x1d, 0x60, 0xec, 0x39, 0xcb, 0xa9, 0xa1, 0xea, 0x38, 0xe1, 0x57, 0xbd,
	0xdf, 0x57, 0x5d, 0x0f, 0x13, 0x6f, 0x7c, 0x9c, 0x40, 0x25, 0xff, 0xc2, 0xdc, 0x87, 0xbe, 0xaf,
	0x0e, 0x3d, 0x4c, 0x3d, 0x67, 0x39, 0xff, 0x7a, 0xb1, 0xfa, 0xe7, 0x1a, 0x2b, 0x81, 0x3f, 0x19,
	0x8a, 0x2c, 0xfe, 0x4c, 0x98, 0x6b, 0x89, 0x9f, 0xb3, 0xb1, 0x0e, 0x42, 0x6c, 0x9a, 0x98, 0xe3,
	0x91, 0x73, 0x36, 0x69, 0xf3, 0xad, 0x0f, 0x2e, 0x12, 0x9e, 0xd1, 0x82, 0xdc, 0xc0, 0x09, 0x59,
	0x90, 0x1b, 0xb4, 0x1b, 0xbd, 0x83, 0x53, 0xb2, 0x1b, 0xbd, 0x43, 0x0b, 0xa5, 0x86, 0x19, 0x59,
	0x28, 0x35, 0x9a, 0x12, 0x3e, 0x30, 0x32, 0x25, 0xec, 0x3c, 0x15, 0xad, 0x61, 0x3e, 0x58, 0xb4,
	0x46, 0xbb, 0x4e, 0x0d, 0xfc, 0x47, 0x76, 0x9d, 0xda, 0x1d, 0xdb, 0xd0, 0x87, 0xff, 0xc9, 0xb6,
	0x21, 0xf5, 0xa6, 0x3b, 0x38, 0x1b, 0x7a, 0x53, 0xbb, 0x37, 0xda, 0xf8, 0xf0, 0x82, 0x2c, 0xda,
	0xd8, 0xdc, 0xc6, 0xdc, 0xc1, 0x39, 0xd9, 0xc6, 0xdc, 0xa1, 0x49, 0x13, 0xc3, 0x4b, 0x32, 0x69,
	0x62, 0x34, 0x1d, 0x69, 0xe0, 0x64, 0x3a, 0xb2, 0x77, 0x4e, 0x8a, 0x14, 0x2e, 0xc8, 0x92, 0x22,
	0x45, 0x2b, 0x44, 0x0e, 0x97, 0x64, 0x85, 0xc8, 0xc9, 0x42, 0x78, 0xf5, 0x6c, 0xf6, 0xfd, 0x0a,
	0x99, 0xc1, 0xd5, 0x60, 0x32, 0xb3, 0xef, 0x97, 0x45, 0xf0, 0x7a, 0x78, 0xbf, 0x2c, 0x42, 0x8b,
	0x33, 0x05, 0x40, 0x16, 0x67, 0x0a, 0xcd, 0xdc, 0xa6, 0xf0, 0x86, 0xcc, 0xdc, 0xd2, 0x5e, 0xa9,
	0xe0, 0xed, 0xf3, 0x3c, 0x9b, 0x5b, 0xab, 0x0c, 0xde, 0x91, 0xad, 0x95, 0xdd, 0x21, 0x53, 0x09,
	0xef, 0x87, 0xff, 0x96, 0x4a, 0xdb, 0x1b, 0x27, 0xf0, 0x61, 0xe8, 0x8d, 0x13, 0x34, 0xe1, 0x0b,
	0xf8, 0x48, 0x26, 0x7c, 0x61, 0x73, 0x89, 0x81, 0x4f, 0x43, 0x2e, 0x31, 0xfc, 0x92, 0x4d, 0x5b,
	0x5f, 0x6c, 0x23, 0xf0, 0x10, 0x6d, 0x81, 0xc9, 0xfb, 0x40, 0xc1, 0x67, 0x4a, 0xde, 0x07, 0xf6,
	0x36, 0xbe, 0x32, 0xb0, 0x20, 0xf3, 0x95, 0xf9, 0xe1, 0xe2, 0xc7, 0xf0, 0xed, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xc7, 0xdb, 0x04, 0x74, 0x19, 0x03, 0x00, 0x00,
}
